// Copyright (C) 2026 The Central Authors.
// SPDX-License-Identifier: AGPL-3.0-only

// Extracts the Material Symbols (Apache-2.0) outlined icons the UI uses into a TypeScript map of
// SVG path data, so icons render as inline <svg> elements without an icon font or innerHTML.
// Usage: npm run icons (after adding a name to ICONS below).
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ICONS = [
  'add',
  'apps',
  'arrow_back',
  'block',
  'bolt',
  'cancel',
  'check',
  'check_circle',
  'check_small',
  'chevron_right',
  'close',
  'cloud',
  'computer',
  'content_copy',
  'dark_mode',
  'dashboard',
  'database',
  'delete',
  'description',
  'developer_board',
  'device_thermostat',
  'dns',
  'download',
  'error',
  'filter_list',
  'folder',
  'group',
  'hard_drive',
  'history',
  'how_to_reg',
  'hub',
  'info',
  'key',
  'keyboard_arrow_down',
  'label',
  'lan',
  'left_panel_close',
  'left_panel_open',
  'light_mode',
  'list',
  'lock',
  'logout',
  'memory',
  'menu',
  'monitoring',
  'more_horiz',
  'more_vert',
  'north',
  'open_in_new',
  'pause_circle',
  'person',
  'play_arrow',
  'policy',
  'power_settings_new',
  'receipt_long',
  'refresh',
  'restart_alt',
  'schedule',
  'search',
  'security',
  'sell',
  'settings',
  'shield',
  'sort',
  'south',
  'speed',
  'stop_circle',
  'storage',
  'swap_vert',
  'sync',
  'terminal',
  'unfold_more',
  'update',
  'upload',
  'verified_user',
  'view_list',
  'visibility',
  'visibility_off',
  'warning',
  'work',
];

const root = dirname(fileURLToPath(import.meta.url));
const dir = join(root, '..', 'node_modules', '@material-symbols', 'svg-400', 'outlined');
const entries = ICONS.map((name) => {
  const svg = readFileSync(join(dir, `${name}.svg`), 'utf8');
  const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length !== 1) throw new Error(`${name}: expected one path, found ${paths.length}`);
  return `  ${name}: '${paths[0]}',`;
});
const out = `// Generated by scripts/icons.mjs from @material-symbols/svg-400. Do not edit.
// Icon path data: Copyright Google LLC, Apache License 2.0.
// SPDX-License-Identifier: Apache-2.0
export const ICONS = {
${entries.join('\n')}
} as const;

export type IconName = keyof typeof ICONS;
`;
writeFileSync(join(root, '..', 'src', 'app', 'shared', 'icons.generated.ts'), out);
console.log(`wrote ${ICONS.length} icons`);
